/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutThemeRouteImport } from './routes/_layout/theme'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReposRouteImport } from './routes/_layout/repos'
import { Route as LayoutPullsRouteImport } from './routes/_layout/pulls'
import { Route as LayoutMembersRouteImport } from './routes/_layout/members'
import { Route as LayoutCommitsRouteImport } from './routes/_layout/commits'
import { Route as LayoutReposIndexRouteImport } from './routes/_layout/repos.index'
import { Route as LayoutMembersIndexRouteImport } from './routes/_layout/members.index'
import { Route as LayoutMembersLoginRouteImport } from './routes/_layout/members.$login'
import { Route as LayoutReposOwnerRepoRouteImport } from './routes/_layout/repos.$owner.$repo'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutThemeRoute = LayoutThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReposRoute = LayoutReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPullsRoute = LayoutPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersRoute = LayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommitsRoute = LayoutCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReposIndexRoute = LayoutReposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutReposRoute,
} as any)
const LayoutMembersIndexRoute = LayoutMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutMembersRoute,
} as any)
const LayoutMembersLoginRoute = LayoutMembersLoginRouteImport.update({
  id: '/$login',
  path: '/$login',
  getParentRoute: () => LayoutMembersRoute,
} as any)
const LayoutReposOwnerRepoRoute = LayoutReposOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => LayoutReposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/setup': typeof SetupRoute
  '/commits': typeof LayoutCommitsRoute
  '/members': typeof LayoutMembersRouteWithChildren
  '/pulls': typeof LayoutPullsRoute
  '/repos': typeof LayoutReposRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/theme': typeof LayoutThemeRoute
  '/members/$login': typeof LayoutMembersLoginRoute
  '/members/': typeof LayoutMembersIndexRoute
  '/repos/': typeof LayoutReposIndexRoute
  '/repos/$owner/$repo': typeof LayoutReposOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/commits': typeof LayoutCommitsRoute
  '/pulls': typeof LayoutPullsRoute
  '/settings': typeof LayoutSettingsRoute
  '/theme': typeof LayoutThemeRoute
  '/': typeof LayoutIndexRoute
  '/members/$login': typeof LayoutMembersLoginRoute
  '/members': typeof LayoutMembersIndexRoute
  '/repos': typeof LayoutReposIndexRoute
  '/repos/$owner/$repo': typeof LayoutReposOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/setup': typeof SetupRoute
  '/_layout/commits': typeof LayoutCommitsRoute
  '/_layout/members': typeof LayoutMembersRouteWithChildren
  '/_layout/pulls': typeof LayoutPullsRoute
  '/_layout/repos': typeof LayoutReposRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/theme': typeof LayoutThemeRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/members/$login': typeof LayoutMembersLoginRoute
  '/_layout/members/': typeof LayoutMembersIndexRoute
  '/_layout/repos/': typeof LayoutReposIndexRoute
  '/_layout/repos/$owner/$repo': typeof LayoutReposOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/commits'
    | '/members'
    | '/pulls'
    | '/repos'
    | '/settings'
    | '/theme'
    | '/members/$login'
    | '/members/'
    | '/repos/'
    | '/repos/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/commits'
    | '/pulls'
    | '/settings'
    | '/theme'
    | '/'
    | '/members/$login'
    | '/members'
    | '/repos'
    | '/repos/$owner/$repo'
  id:
    | '__root__'
    | '/_layout'
    | '/setup'
    | '/_layout/commits'
    | '/_layout/members'
    | '/_layout/pulls'
    | '/_layout/repos'
    | '/_layout/settings'
    | '/_layout/theme'
    | '/_layout/'
    | '/_layout/members/$login'
    | '/_layout/members/'
    | '/_layout/repos/'
    | '/_layout/repos/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/theme': {
      id: '/_layout/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof LayoutThemeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repos': {
      id: '/_layout/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof LayoutReposRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pulls': {
      id: '/_layout/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof LayoutPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members': {
      id: '/_layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/commits': {
      id: '/_layout/commits'
      path: '/commits'
      fullPath: '/commits'
      preLoaderRoute: typeof LayoutCommitsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repos/': {
      id: '/_layout/repos/'
      path: '/'
      fullPath: '/repos/'
      preLoaderRoute: typeof LayoutReposIndexRouteImport
      parentRoute: typeof LayoutReposRoute
    }
    '/_layout/members/': {
      id: '/_layout/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof LayoutMembersIndexRouteImport
      parentRoute: typeof LayoutMembersRoute
    }
    '/_layout/members/$login': {
      id: '/_layout/members/$login'
      path: '/$login'
      fullPath: '/members/$login'
      preLoaderRoute: typeof LayoutMembersLoginRouteImport
      parentRoute: typeof LayoutMembersRoute
    }
    '/_layout/repos/$owner/$repo': {
      id: '/_layout/repos/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof LayoutReposOwnerRepoRouteImport
      parentRoute: typeof LayoutReposRoute
    }
  }
}

interface LayoutMembersRouteChildren {
  LayoutMembersLoginRoute: typeof LayoutMembersLoginRoute
  LayoutMembersIndexRoute: typeof LayoutMembersIndexRoute
}

const LayoutMembersRouteChildren: LayoutMembersRouteChildren = {
  LayoutMembersLoginRoute: LayoutMembersLoginRoute,
  LayoutMembersIndexRoute: LayoutMembersIndexRoute,
}

const LayoutMembersRouteWithChildren = LayoutMembersRoute._addFileChildren(
  LayoutMembersRouteChildren,
)

interface LayoutReposRouteChildren {
  LayoutReposIndexRoute: typeof LayoutReposIndexRoute
  LayoutReposOwnerRepoRoute: typeof LayoutReposOwnerRepoRoute
}

const LayoutReposRouteChildren: LayoutReposRouteChildren = {
  LayoutReposIndexRoute: LayoutReposIndexRoute,
  LayoutReposOwnerRepoRoute: LayoutReposOwnerRepoRoute,
}

const LayoutReposRouteWithChildren = LayoutReposRoute._addFileChildren(
  LayoutReposRouteChildren,
)

interface LayoutRouteChildren {
  LayoutCommitsRoute: typeof LayoutCommitsRoute
  LayoutMembersRoute: typeof LayoutMembersRouteWithChildren
  LayoutPullsRoute: typeof LayoutPullsRoute
  LayoutReposRoute: typeof LayoutReposRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutThemeRoute: typeof LayoutThemeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCommitsRoute: LayoutCommitsRoute,
  LayoutMembersRoute: LayoutMembersRouteWithChildren,
  LayoutPullsRoute: LayoutPullsRoute,
  LayoutReposRoute: LayoutReposRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutThemeRoute: LayoutThemeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
