/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReposRouteImport } from './routes/_layout/repos'
import { Route as LayoutPullsRouteImport } from './routes/_layout/pulls'
import { Route as LayoutMembersRouteImport } from './routes/_layout/members'
import { Route as LayoutCommitsRouteImport } from './routes/_layout/commits'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReposRoute = LayoutReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPullsRoute = LayoutPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersRoute = LayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommitsRoute = LayoutCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/setup': typeof SetupRoute
  '/commits': typeof LayoutCommitsRoute
  '/members': typeof LayoutMembersRoute
  '/pulls': typeof LayoutPullsRoute
  '/repos': typeof LayoutReposRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/commits': typeof LayoutCommitsRoute
  '/members': typeof LayoutMembersRoute
  '/pulls': typeof LayoutPullsRoute
  '/repos': typeof LayoutReposRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/setup': typeof SetupRoute
  '/_layout/commits': typeof LayoutCommitsRoute
  '/_layout/members': typeof LayoutMembersRoute
  '/_layout/pulls': typeof LayoutPullsRoute
  '/_layout/repos': typeof LayoutReposRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/commits'
    | '/members'
    | '/pulls'
    | '/repos'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/commits'
    | '/members'
    | '/pulls'
    | '/repos'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/setup'
    | '/_layout/commits'
    | '/_layout/members'
    | '/_layout/pulls'
    | '/_layout/repos'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repos': {
      id: '/_layout/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof LayoutReposRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pulls': {
      id: '/_layout/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof LayoutPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members': {
      id: '/_layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/commits': {
      id: '/_layout/commits'
      path: '/commits'
      fullPath: '/commits'
      preLoaderRoute: typeof LayoutCommitsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCommitsRoute: typeof LayoutCommitsRoute
  LayoutMembersRoute: typeof LayoutMembersRoute
  LayoutPullsRoute: typeof LayoutPullsRoute
  LayoutReposRoute: typeof LayoutReposRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCommitsRoute: LayoutCommitsRoute,
  LayoutMembersRoute: LayoutMembersRoute,
  LayoutPullsRoute: LayoutPullsRoute,
  LayoutReposRoute: LayoutReposRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
